### ISSUE TITLE
What are the correct upload settings and inclusion settings to use?

### ISSUE THREAD

**Issue by stx** [getsentry/sentry-dart-plugin#33]
Thanks for your work on this great plugin!

The docs list these options:

```
  upload_native_symbols: true
  upload_source_maps: false
  include_native_sources: false
```

It's not clear to us which of these options to use.

We build apps for both mobile and web in one go (with --source-maps enabled on the web release) and then run `flutter packages pub run sentry_dart_plugin`, so I presume we want to enable all three options? Is there a reason why we *wouldn't* want to enable one of these options?

I think it'd be really nice to document what to do here. 🙏

**Comment by marandaneto** [comment]
@stx thanks for raising this.

See https://docs.sentry.io/platforms/flutter/upload-debug/
The readme actually explains each of the options and then it's up to your needs, but TLDR is (in your use case):

`upload_native_symbols`, you need it since you want to symbolicate Native events (e.g. iOS hard crashes).
`upload_source_maps`, you need it since you want to symbolicate Web events (from JS to Dart).
`include_native_sources`, that's optional, if you want to see source code context, enable it, otherwise, you see only class/method names and line numbers.

**Comment by stx** [comment]
@marandaneto Thank you! We saw the docs but it was your explanation here that was missing and is perfect. :)
