### ISSUE TITLE
Release name mismatch between plugin and flutter package

### ISSUE THREAD

**Issue by Maczuga** [getsentry/sentry-dart-plugin#82]
### Environment

`sentry_dart_plugin: ^1.0.0-beta.5`

### Steps to Reproduce

1. `flutter build appbundle --flavor staging --obfuscate --split-debug-info="build/app/outputs/symbols"` (you can omit the flavor)
2. `flutter packages pub run sentry_dart_plugin`
3. Do **NOT** change the `options.release` in `SentryFlutter.init`

### Expected Result

Release name from running plugin `flutter packages pub run sentry_dart_plugin` should match the release name coming from default `SentryFlutter.init`. 

So if my package (not flutter project, actually released package) is com.example.something, and version is 0.2.0+13 (I am ignoring a possibility of versionNameSuffix from flavors for now) - then the default release name on sentry should match the **package name**, not the flutter project name. Otherwise we end up with different non-matching releases in Sentry.

Ideally this plugin should be able to generate same Sentry release name as flutter plugin when `options.release` is not specified - since those can be different depending on flavor or platform.

### Actual Result

Currently plugin is ignoring the package name and simply uses pubspec `name` value. This kinda invalidates flavors.
![image](https://user-images.githubusercontent.com/544349/220869978-0e275c84-7bf9-496e-a0c6-92b6e5eb2f5b.png)

Top release was generated by plugin, bottom was from launching released in Play Store app. Names have been changed for bug reporting purposes.

Overall it seems that you can't even replace the "pubspec_name" from screenshot anyhow in plugin - even if you change the sentry.release prop in pubspec.yaml (I have changed the `release` to "something@123" and the pubspec name was still used, while "something@123" was in version row).

**Comment by marandaneto** [comment]
@Maczuga the release created by launching the App detects the release name, version, and build number at runtime while this plugin relies on the `pubspec` only.
If you read this [table](https://github.com/getsentry/sentry-dart-plugin#available-configuration-fields), you can see that:

> The release version for source maps, it should match the release set by the SDK

The plugin does not have access to the runtime of the app so we cannot guarantee that the releases will match, that's why we offer the option of overwriting this value via the `release` config in the `pubspec` or the `SENTRY_RELEASE` env. var.

Can you copy-paste your `sentry` config in the `pubspec` file?

**Comment by marandaneto** [comment]
@Maczuga any input here?

**Comment by marandaneto** [comment]
Alright, closing this, we'll make sure to be explicit about that in our docs (versioning should match etc).
